dist: trusty
sudo: required

language: scala

git:
  depth: 3
  quiet: true

env:
  - JAVA_OPTS="-Dsbt.log.noformat=true"
  
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.1

jdk:
  - openjdk8
  - openjdk11
